Switch to pynose for tests
With Python versions later than 3.9, nose tests will break due
to

  nose AttributeError: module 'collections' has no attribute 'Callable'

Switching to pynose which accounts for later Python versions
fixes the problem.